# Generated by Django 4.2.4 on 2023-09-01 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_alter_homefields_subtittle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homefields',
            name='content',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='homefields',
            name='faceImg',
            field=models.ImageField(upload_to='core/assets/img/'),
        ),
    ]
